### ISSUE TITLE
ConcurrentModificationException when setting up

### ISSUE THREAD

**Issue by mrcurly** [jamesdbloom/mockserver#136]
I setup mockServer with a client.reset() followed immediately by sending 4 expectations, and it fails with this error:

ConcurrentModificationException

```java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859) ~[na:1.7.0_79]
	at java.util.ArrayList$Itr.next(ArrayList.java:831) ~[na:1.7.0_79]
	at com.google.common.collect.Iterators.indexOf(Iterators.java:777) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at com.google.common.collect.Iterators.any(Iterators.java:684) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at com.google.common.collect.Iterables.any(Iterables.java:623) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at com.google.common.collect.Collections2$FilteredCollection.isEmpty(Collections2.java:186) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.mock.MockServerMatcher.when(MockServerMatcher.java:43) ~[mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.mockserver.MockServerHandler.channelRead0(MockServerHandler.java:69) [mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.mockserver.MockServerHandler.channelRead0(MockServerHandler.java:34) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:147) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:242) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:147) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) [mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.server.unification.PortUnificationHandler.switchToHttp(PortUnificationHandler.java:88) [mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.server.unification.PortUnificationHandler.channelRead0(PortUnificationHandler.java:39) [mockserver-netty-jar-with-dependencies.jar:na]
	at org.mockserver.server.unification.PortUnificationHandler.channelRead0(PortUnificationHandler.java:20) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:847) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) [mockserver-netty-jar-with-dependencies.jar:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [mockserver-netty-jar-with-dependencies.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]```

**Comment by jamesdbloom** [comment]
I assume this happened when you were registering two exceptions at the same time.  I have fixed this, it looks like using Guava exaggerated a concurrency issue with adding exceptions.  This is because Guava delays actions such a filtering until the collection is next accessed.  I have switched away from Guava for this functionality and fixed the concurrency issue.

**Comment by khanh-nguyen** [comment]
@jamesdbloom I'm still experiencing this error when creating expectations with mockserver@3.9.15. I opened a new [issue#138](https://github.com/jamesdbloom/mockserver/issues/138) for it.
