### ISSUE TITLE
CORS: Allow Credentials

### ISSUE THREAD

**Issue by antoninvogt** [jamesdbloom/mockserver#505]
I am having trouble testing an application which makes CORS requests with credentials.

I know this has been discussed in #401, but it appears that the solution proposed there does not work everywhere.

This is what I believe happens in our case:

1. The application runs on `localhost:1234`.
1. The app makes a cross-origin request to `localhost:2345` with a [credentials mode](https://fetch.spec.whatwg.org/#concept-request-credentials-mode) of `include`, using `fetch("http://localhost:2345/some/resource", { credentials: "include" })`.
1. Mock-Server does not recognize that the request includes credentials and returns a response with its global default CORS headers.
    * The response has an `Access-Control-Allow-Origin` header value of `*`.
    * The response has no `Access-Control-Allow-Credentials` header.
1. The browser determines that it is not safe to give web content access to the response.

The browser turns down the response with the following error message.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘http://localhost:2345/some/resource’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).
```

(See MDN's [CORS - Credentialed requests and wildcards](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Credentialed_requests_and_wildcards) for details.)

Regardless, the response would have been hidden from web content because the `Access-Control-Allow-Credentials` header is missing (see [CORS - Access-Control-Allow-Credentials](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Access-Control-Allow-Credentials)).

## Why Does the Existing Solution Not Work? ##

If I understand the change in https://github.com/jamesdbloom/mockserver/commit/16647d8f7810f088a1060c8b0dedf276115337de#diff-6649b9bf089ed61ac03004199e753e0bR30 correctly, the idea was to mirror the specific origin and append the credentials header if the request comes with an `Access-Control-Allow-Credentials` header.

However, this header is not actually sent by the client, but by the server to tell the client that the response is safe to use (see [Fetch spec - 3.2.5. CORS protocol and credentials](https://fetch.spec.whatwg.org/#cors-protocol-and-credentials)).

This is what the actual request looks like, triggered by the browser's native `fetch` API:

```
GET /some/resource HTTP/1.1
Host: localhost:2345
Connection: keep-alive
Origin: http://localhost:1234
User-Agent: <SOME-USER-AGENT>
Accept: */*
Referer: http://localhost:1234/some-page.html
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,de;q=0.8
Cookie: tasty_secrets=abc123
```

To which Mock-Server responds with:

```
HTTP/1.1 200 OK
content-type: application/json; charset=utf-8
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: CONNECT, DELETE, GET, HEAD, OPTIONS, POST, PUT, TRACE
Access-Control-Allow-Headers: Allow, Content-Encoding, Content-Length, Content-Type, ETag, Expires, Last-Modified, Location, Server, Vary
Access-Control-Expose-Headers: Allow, Content-Encoding, Content-Length, Content-Type, ETag, Expires, Last-Modified, Location, Server, Vary
Access-Control-Max-Age: 300
X-CORS: MockServer CORS support enabled by default, to disable ConfigurationProperties.enableCORSForAPI(false) or -Dmockserver.disableCORS=false
connection: keep-alive
content-length: 1234
```

### Origin ###

Instead of defaulting to `Access-Control-Allow-Origin: *`, Mock-Server could always mirror the specific origin of the request if present.

As far as I can tell, this should work the same for any requests where the `*` wildcard would be sufficient, and be an improvement for any others.

### Credentials ###

From the [fetch spec](https://fetch.spec.whatwg.org/#cors-protocol-and-credentials):

> A request’s credentials mode is not necessarily observable on the server; [...] Note that [...] a CORS-preflight request never includes credentials.
> The server developer therefore needs to decide whether or not responses "tainted" with credentials can be shared. And also needs to decide if requests necessitating a CORS-preflight request can include credentials.

Two potential fixes that I can see:

Mock-Server could...
1. ... always include a `Access-Control-Allow-Credentials: true` header on every response, or
1. ... allow the test author a way to explicitly set the `Access-Control-Allow-Credentials` header in an expectation, even if Mock-Server's default CORS behavior is enabled.

I would personally lean towards the first option as it requires the least amount of configuration on the test author's end.

For the second option, [preflighted requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests) would probably require additional rules for `OPTIONS` requests, which might add noise to the test suite.

Thanks a bunch for looking into this - appreciate the work you're putting into this. Let me know if there is something that I can help out with.

**Comment by jamesdbloom** [comment]
A related issue that should all be fixed at the same time #441

**Comment by jamesdbloom** [comment]
new feature requests now prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/tmLO2bEE/24-allow-all-cors-header-values-to-be-configurable

**Comment by malins** [comment]
Hello, in my opinion this issue is not fixed, and the analysis from antoninvogt is still correct. Browsers never send `Access-Control-Allow-Credentials` in their preflight request.

In addition, `Access-Control-Allow-Credentials:true` is only credited by the browser if the hostname is listed in Access-Control-Allow-Origin, and the origin value is currently not configurable.
