### ISSUE TITLE
Documentation: error for regex body expectation

### ISSUE THREAD

**Issue by maksmi** [jamesdbloom/mockserver#506]
Found some error in documentation for creating expectation with regex body compare

```
"httpRequest" : {
    "body" : "starts_with_.*"
  },
```
while it should be like
```
"httpRequest" : {
    "type" : "REGEX",
    "regex" : "starts_with_.*"
  },
```
same goes for js and java

**Comment by jamesdbloom** [comment]
fixed

**Comment by benzman81** [comment]
Still not correct. Only working with:

`
"httpRequest" : {
    "body" : {
        "type" : "REGEX",
        "regex" : "starts_with_.*"
    }
  },
`
